from .frontend_endpoints.githublogin import githublogin_bp
from .frontend_endpoints.api_player import api_player_bp
from .frontend_endpoints.api_quests import api_quests_bp
from .backend_endpoints.index import index_bp
from .frontend_endpoints.health import health_bp
from .frontend_endpoints.auth_me import auth_me_bp
from .frontend_endpoints.auth_logout import auth_logout_bp
from .frontend_endpoints.ai_problems import ai_problems_bp
from .frontend_endpoints.ai_runner import ai_runner_bp
from .frontend_endpoints.ai_comprehensive import ai_comprehensive_bp
from .backend_endpoints.register import register_bp
from .backend_endpoints.dashboard import dashboard_bp
from .frontend_endpoints.auth import auth_bp
from .backend_endpoints.login import login_bp